version: "3.7"

services:
  server_task_5:
    build: ../task5
    container_name: server_task_5
    tty: true
  part6:
    image: nginx
    container_name: server_task6
    ports:
      - 80:8080
    depends_on:
      - server_task_5
    volumes:
      - ./part_6/nginx.conf:/etc/nginx/nginx.conf